"""Add description column to bucketlist

Revision ID: 23654a528cc0
Revises: 7cbeff7fd6e3
Create Date: 2017-04-10 08:01:57.618769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23654a528cc0'
down_revision = '7cbeff7fd6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bucketlist_title'), 'bucketlist', ['title'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_bucketlist_title'), table_name='bucketlist')
    # ### end Alembic commands ###
